// ALP LED API Sample Multi-Color.cpp : Defines the entry point for the console application.
//
#include "ALP Streaming Sample.h"

int _tmain(int argc , _TCHAR*  argv [])
{
// Output general information//////////////////////////////////////////////////
	_tprintf( _T("ALP Streaming Sample.exe \r\n") );
	_tprintf( _T("This sample program loads image files placed in a specified folder\r\nand transfers them to the SDRAM of the ALP controller board.\r\n") );
	_tprintf( _T("Concurrent projection is achieved by using multiple memory buffers.\r\n") );
	_tprintf( _T("This program is intended to be used together with the ALP ImageConverter Sample program.\r\n") );
	_tprintf( _T("\r\nInput parameters: \r\n") );
	_tprintf( _T("1. Height of the source images (default=dmd height).\r\n") );
	_tprintf( _T("2. Frame rate in frames per second (default=30fps).\r\n") );
	_tprintf( _T("3. Path of input directory (default=directory of executable). If \"\" is specified, the default path is used.\r\n   The frames must be packed in files with an \".alp\" extension (generated by the ALP ImageConverter Sample)\r\n") );
	_tprintf( _T("   and must be formatted in the ALP_DATA_BINARY_TOPDOWN data format.\r\n   After every \".alp\" file in the directory is loaded, loading continues with the first \".alp\" file again.\r\n") );
	_tprintf( _T("4. Number of frames per buffer. If the number is too small, the transfer time will be reduced.\r\n   However, reduction of the buffer size might be necessary, if the program fails to allocate enough memory.\r\n") );
	_tprintf( _T("\r\n") );


// Parse commandline arguments and initialize variables /////////////////////////
	long nLineNumber = argc > 1 ? _ttoi(argv[1]) : 0;
	long nFramerate  = argc > 2 ? _ttoi(argv[2]) : 30;	// frames per second
	CString directoryNameLOAD = (argc > 3 && (CString)argv[3]!=_T("")) ? (CString)argv[3] : getExeDir();
	long nFramesPerBuffer = argc > 4 ? _ttoi(argv[4]) : 3000;

	const long nBufferNumber = 3;					// Triple Buffer
	bool bBufferCommitted[nBufferNumber], bBufferLoaded[nBufferNumber];

	for(long i=0; i < nBufferNumber; i++ )
	{
		bBufferCommitted[i] = false;
		bBufferLoaded[i] = false;
	}
	
	long nProjIndex = 0;
	std::unique_ptr<HANDLE[]> hThreads(new HANDLE[2]);
	
	ALP_ID AlpDevId, AlpSeqId[nBufferNumber];
	long nDmdWidth(0), nDmdHeight(0);

	std::unique_ptr<UCHAR[]> pFrameData;


// General ALP API stuff //////////////////////////////////////////////////////
	// Initialize the ALP device
	VERIFY_ALP_NO_ECHO( AlpDevAlloc( 0, 0, &AlpDevId ) );
	VERIFY_ALP_NO_ECHO( AlpDevInquire( AlpDevId, ALP_DEV_DISPLAY_WIDTH, &nDmdWidth ) );
	VERIFY_ALP_NO_ECHO( AlpDevInquire( AlpDevId, ALP_DEV_DISPLAY_HEIGHT, &nDmdHeight ) );
	_tprintf( _T("Note: DMD size: %i x %i pixels\r\n"), nDmdWidth, nDmdHeight );
	if(nLineNumber == 0)  nLineNumber = nDmdHeight;
	if(nLineNumber > nDmdHeight || nLineNumber < 0)
	{ 
		_tprintf( _T("Error: nLineNumber invalid.\r\n"));
		AlpDevFree(AlpDevId);
		Pause();
		return 1;
	}
	long nLineOffset = (nDmdHeight - nLineNumber) / 2;
	long nBufferSize = nFramesPerBuffer*nDmdWidth*nLineNumber/8;
	
	try
	{
		pFrameData.reset(new UCHAR[nBufferNumber*nBufferSize]);
	}
	catch(...)
	{
		_tprintf( _T("Error: Allocation of frame buffer failed probably because of lacking memory. Try to reduce the buffer size.\r\n"));
		AlpDevFree(AlpDevId);
		Pause();
		return 1;
	}

	VERIFY_ALP_NO_ECHO(AlpProjControl(AlpDevId, ALP_PROJ_QUEUE_MODE, ALP_PROJ_SEQUENCE_QUEUE));

	// Setup AOI
	VERIFY_ALP_NO_ECHO(AlpDevControl(AlpDevId, ALP_SEQ_DMD_LINES, MAKELONG(nLineOffset, nLineNumber)));

	// Allocate sequences and configure them
	for(long i=0; i < nBufferNumber; i++)
	{
		// Allocation and data format
		VERIFY_ALP_NO_ECHO( AlpSeqAlloc( AlpDevId, 1, nFramesPerBuffer, &AlpSeqId[i] ) );
		VERIFY_ALP_NO_ECHO( AlpSeqControl(AlpDevId, AlpSeqId[i], ALP_BIN_MODE, ALP_BIN_UNINTERRUPTED));
		VERIFY_ALP_NO_ECHO( AlpSeqControl(AlpDevId, AlpSeqId[i], ALP_DATA_FORMAT, ALP_DATA_BINARY_TOPDOWN));

		// Scrolling and AOI 
		VERIFY_ALP_NO_ECHO( AlpSeqControl(AlpDevId, AlpSeqId[i], ALP_SEQ_DMD_LINES, MAKELONG(nLineOffset, nLineNumber)));
		VERIFY_ALP_NO_ECHO( AlpSeqControl(AlpDevId, AlpSeqId[i], ALP_SCROLL_FROM_ROW, 0));
		VERIFY_ALP_NO_ECHO( AlpSeqControl(AlpDevId, AlpSeqId[i], ALP_SCROLL_TO_ROW, (nFramesPerBuffer-1)*nLineNumber));
		VERIFY_ALP_NO_ECHO( AlpSeqControl(AlpDevId, AlpSeqId[i], ALP_LINE_INC, nLineNumber));

		// Timing
		VERIFY_ALP_NO_ECHO( AlpSeqTiming( AlpDevId, AlpSeqId[i], ALP_DEFAULT, 1000000/nFramerate /* convert fps to µs */, ALP_DEFAULT, 1000000/nFramerate-1 /* Synch Pulse Width = PictureTime-1µs */, ALP_DEFAULT ) );
	}
	
	_tprintf( _T("Note: Sequence timing: PicTime=%i us, i.e. Frame rate=%i fps\r\n"), 1000000/nFramerate, nFramerate );	// convert ms to Hz


// Start threads for Image loading and AlpSeqPutEx ////////////////////////////
	bool bExit = false;
	bool bError = false;
	bool bFirstSpeedWarning = true;

	HANDLE eBufferLoadDoneCommitCleared[2];// = new HANDLE[2];
	eBufferLoadDoneCommitCleared[0] = CreateEvent(NULL, FALSE, FALSE, NULL);
	eBufferLoadDoneCommitCleared[1] = CreateEvent(NULL, FALSE, FALSE, NULL);
	HANDLE* eBufferLoadDone =  &eBufferLoadDoneCommitCleared[0];
	HANDLE eBufferLoadCleared = CreateEvent(NULL, FALSE, FALSE, NULL);
	HANDLE* eBufferCommitCleared = &eBufferLoadDoneCommitCleared[1];
	HANDLE eBufferCommitDone = CreateEvent(NULL, FALSE, FALSE, NULL);

	tThreadFunctionVariables ThreadFunctionVariables(AlpDevId, AlpSeqId, bBufferLoaded, bBufferCommitted, &bExit, &bError, nBufferSize, nFramesPerBuffer, nBufferNumber, pFrameData.get(), directoryNameLOAD, eBufferLoadDone, &eBufferCommitDone, &eBufferLoadCleared, eBufferCommitCleared);

	hThreads[0] = CreateThread( NULL, 0, ThreadFunctionLoadFramesFromFile, &ThreadFunctionVariables, 0, NULL );
	hThreads[1] = CreateThread( NULL, 0, ThreadFunctionAlpSeqPut, &ThreadFunctionVariables, 0, NULL );


// Start projection loop //////////////////////////////////////////////////////
	_tprintf( _T("Note: Starting projection, press any key to exit.\r\n") );

	while(!_kbhit())
	{
		if(bBufferCommitted[nProjIndex])
		{
			// Check if AlpSeqPut is to slow (i.e. no sequence is running for projection)
			tAlpProjProgress AlpProjProgress;
			AlpProjProgress.SequenceId = ALP_INVALID_ID;
			VERIFY_ALP_NO_ECHO(AlpProjInquireEx(AlpDevId, ALP_PROJ_PROGRESS, &AlpProjProgress));

			if(AlpProjProgress.SequenceId == ALP_INVALID_ID && !bFirstSpeedWarning)	// First warning is supressed, because it will always trigger
				_tprintf( _T("Warning: Projection is paused because AlpSeqPut or the loading of images is to slow. Reduce frame rate or image height for continuous projection\r\n") );

			bFirstSpeedWarning = false;

			if(!bBufferLoaded[nProjIndex])
				_tprintf( _T("Warning: Buffer is committed but not loaded.\r\n") );

			// Start projection
			VERIFY_ALP_NO_ECHO(AlpProjStart(AlpDevId, AlpSeqId[nProjIndex]));
			bBufferCommitted[nProjIndex] = false;
			SetEvent(*eBufferCommitCleared);
			bBufferLoaded[nProjIndex] = false;
			SetEvent(eBufferLoadCleared);
			nProjIndex = (nProjIndex+1) % nBufferNumber;
		}
		else
			WaitForSingleObject(eBufferCommitDone, INFINITE);

		// Check if threads reported an error
		if(bError)
		{
			Pause();
			break;
		}
	}

	// End thread for AlpSeqPut and free device
	// Set all events to avoid death locks
	*ThreadFunctionVariables.bExit = true;
	SetEvent(*eBufferCommitCleared);
	SetEvent(eBufferLoadCleared);
	SetEvent(*eBufferLoadDone);
	SetEvent(eBufferCommitDone);

	_tprintf( _T("Info: Waiting for threads to finish.\r\n"));
	WaitForMultipleObjects(3, hThreads.get(), true, INFINITE);
	
	AlpDevHalt(AlpDevId);
	
	for(long i=0; i < nBufferNumber; i++)
	{
		AlpSeqFree( AlpDevId, AlpSeqId[i]);
	}

	AlpDevFree(AlpDevId);

	_tprintf( _T("Info: Exiting ALP Streaming Sample.\r\n"));
}

DWORD WINAPI ThreadFunctionLoadFramesFromFile( LPVOID lpThreadParameter )
{
	tThreadFunctionVariables &pInput = *static_cast<tThreadFunctionVariables*>(lpThreadParameter);
	long nLoadIndex = 0;
	long nBufferLeft =  pInput.nBufferSize;

	WIN32_FIND_DATA file;
	HANDLE hFileHandle = NULL;


	while(true)
	{	
		// Get next file
		do
		{
			if(!hFileHandle || !FindNextFile(hFileHandle, &file))	// Last file in directory? Then restart with first file
			{
				hFileHandle = FindFirstFile(pInput.directoryNameLOAD + _T("\\*"), &file);
				
				if(hFileHandle == INVALID_HANDLE_VALUE)	// Still no file? Error!
				{
					*pInput.bError = true;
					SetEvent(*pInput.eBufferLoadDone);	// SetEvent to avoid death locks
					return 1;
				}
			}

			if(*pInput.bExit)
				return 0;

		} while( !( (file.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY ) == 0 && PathMatchSpecW(file.cFileName, L"*.alp")));


		// Load data from file
		{
			std::ifstream InputFile(pInput.directoryNameLOAD + _T("\\") + file.cFileName, std::ios::binary);
			
			if(!InputFile.is_open())
			{
				_tprintf( _T("Error: Cannot open file.\r\n") );
				*pInput.bError = true;
				SetEvent(*pInput.eBufferLoadDone);	// SetEvent to avoid death locks
				return 1;
			}

			while(InputFile.peek() != EOF && !InputFile.eof())
			{
				if(!pInput.bBufferLoaded[nLoadIndex])
				{
					long nBufferOffset = (nLoadIndex+1)*pInput.nBufferSize - nBufferLeft;

					InputFile.read((char*)(pInput.pFrameData + nBufferOffset), nBufferLeft);
					nBufferLeft = nBufferLeft - (long)InputFile.gcount();

					if(0 == nBufferLeft)
					{
						pInput.bBufferLoaded[nLoadIndex] = true;
						nLoadIndex = (nLoadIndex+1) % pInput.nBufferNumber;
						nBufferLeft =  pInput.nBufferSize;
						SetEvent(*pInput.eBufferLoadDone);
					}
				}
				else
				{
					WaitForSingleObject(*pInput.eBufferLoadCleared, INFINITE);
				}

				if(*pInput.bExit)
				{
					InputFile.close();
					return 0;
				}
			}

			InputFile.close();
		}
	}

	return 0;
}

DWORD WINAPI ThreadFunctionAlpSeqPut( LPVOID lpThreadParameter )
{
	tThreadFunctionVariables &pInput = *static_cast<tThreadFunctionVariables*>(lpThreadParameter);
	long nSeqPutIndex = 0;
	long nRet = ALP_OK;

	tAlpLinePut AlpLinePut;
	AlpLinePut.TransferMode = ALP_PUT_LINES;
	AlpLinePut.PicOffset = ALP_DEFAULT;
	AlpLinePut.PicLoad = pInput.nFramesPerBuffer;
	AlpLinePut.LineOffset = ALP_DEFAULT;
	AlpLinePut.LineLoad = ALP_DEFAULT;


	while(!*pInput.bExit)
	{
		if(pInput.bBufferLoaded[nSeqPutIndex] & !pInput.bBufferCommitted[nSeqPutIndex])
		{
			// Check progress of projection to determine if next buffer is still used for projection
			tAlpProjProgress AlpProjProgress;
			if(ALP_OK != (nRet = AlpProjInquireEx(pInput.AlpDevId, ALP_PROJ_PROGRESS, &AlpProjProgress)))
			{
				AlpError(nRet, _T("AlpProjInquireEx"), true);
				*pInput.bError = true;
				SetEvent(*pInput.eBufferCommitDone);	// SetEvent to avoid death locks
				return 1;
			}


			// Transfer data with AlpSeqPutEx
			if(AlpProjProgress.SequenceId != pInput.AlpSeqId[nSeqPutIndex])	// Sequence associated with next buffer is not used for projection
			{
				if(ALP_OK != (nRet = AlpSeqPutEx(pInput.AlpDevId, pInput.AlpSeqId[nSeqPutIndex], &AlpLinePut, pInput.pFrameData + nSeqPutIndex*pInput.nBufferSize)))
				{
					AlpError(nRet, _T("AlpSeqPutEx"), true);
					*pInput.bError = true;
					SetEvent(*pInput.eBufferCommitDone);	// SetEvent to avoid death locks
					return 1;
				}

				pInput.bBufferCommitted[nSeqPutIndex] = true;
				nSeqPutIndex = (nSeqPutIndex+1) % pInput.nBufferNumber;
				SetEvent(*pInput.eBufferCommitDone);
			}
		}
		else
			WaitForMultipleObjects(2, pInput.eBufferLoadDone, false, INFINITE);
	}

	return 0;
}

CString getExeDir()
{
	TCHAR buffer[MAX_PATH] = { 0 };
	GetModuleFileName( NULL ,buffer, MAX_PATH);
	std::wstring::size_type pos = std::wstring(buffer).find_last_of(L"\\/");
	
	CString str = CString(buffer);
	str.Truncate(pos);
	return str;
}